---
- name: Gen new mac
  vars:
    gen_new_macaddress: "openssl rand -hex 6 | sed 's/\\(..\\)/\\1:/g; s/:$//'"
    # my_list_macaddresses: ['22:a6:c0:e7:73:36','a5:dd:a4:ae:12:6a','89:dc:bc:32:b7:f2'] # for cp1, wr1, wr2
  shell:
    cmd: "{{gen_new_macaddress}}"
  register: new_macaddr
  
- set_fact:
    home_dir: "{{ lookup('env', 'HOME') }}"
  
- name: Change macaddress for utm-vms for file {{fname}}
  vars:
    path_to_vms: "{{ home_dir }}/Library/Containers/com.utmapp.UTM/Data/Documents/{{ vm_macaddr.vmname }}.utm/config.plist"
  replace:
    path: "{{ path_to_vms }}"
    regexp: '<string>(DE\:2F\:83\:8F\:F9\:DE)</string>'
    replace: '<string>{{ vm_macaddr.macaddr }}</string>'
    # replace: '<string>{{ new_macaddr.stdout_lines[0] }}</string>'
