- name: Add repositorys for helm
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - name: "cilium"
      url: "https://helm.cilium.io/"
    - name: "metallb"
      url: "https://metallb.github.io/metallb"
    - name: "ingress-nginx"
      url: "https://kubernetes.github.io/ingress-nginx"
    - name: "prometheus-community"
      url: "https://prometheus-community.github.io/helm-charts"
