- name: Create a directory "metallb" if it does not exist
  ansible.builtin.file:
    path: /home/dv/myfiles/kuber/metallb
    state: directory
    mode: '0755'
    owner: dv
    group: dv

- name: Copy metallb manifest L2-advertizeng file with owner and permissions
  ansible.builtin.copy:
    src: metallb-ip-range-manifest.yaml
    dest: /home/dv/myfiles/kuber/metallb
    owner: dv
    group: dv
    mode: '0644'
    
- name: Copy metallb manifest L2-advertizeng file with owner and permissions
  ansible.builtin.copy:
    src: metallb-l2adv-manifest.yaml
    dest: /home/dv/myfiles/kuber/metallb
    owner: dv
    group: dv
    mode: '0644'
    
- name: Install Helm charts MetalLB
  kubernetes.core.helm:
    name: "metallb"
    chart_ref: "metallb/metallb"
    release_namespace: "metallb-system"
    create_namespace: yes
    # wait: true

