---
- name: Install Helm charts Ingress-Nginx
  kubernetes.core.helm:
    name: "ingress-nginx"
    chart_ref: "ingress-nginx/ingress-nginx"
    release_namespace: "ingress-nginx"
    create_namespace: yes
    kubeconfig: /home/dv/.kube/config
    verify_ssl: false
    wait: true
