apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-class
  resources:
    requests:
      storage: 250Mi
  # volumeMode: Filesystem
