kind: Service
apiVersion: v1
metadata:
  name: app-nginx-service-nodeport
spec:
  type: NodePort
  selector:
    app: app-nginx
  #type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80