apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client # your storage class name
  resources:
    requests:
      storage: 1G
  # volumeMode: Filesystem
