apiVersion: v1
kind: Pod
metadata:
  name: test-volume
  labels:
    app: test-vm
spec:
  containers:
    - name: alpine
      image: alpine:latest
#      imagePullPolicy: IfNotPresent
      command:
        - touch
        - /data/test
      volumeMounts:
        - mountPath: /data
          name: nfs-volume
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.0.186
        path: /mnt/nfs-share
        readOnly: no
  restartPolicy: Always
