apiVersion: v1
kind: Pod
metadata:
  name: test-app-name-pod
  labels:
    enviroment: lb-dev
    app: lb-nginx
    test: "yes"
spec:
  containers:
    - name: hostname-name-container
      image: nginx
      ports:
        - containerPort: 80