apiVersion: v1
kind: Pod
metadata:
  name: test-app-2
  labels:
    app: hostname
spec:
  containers:
    - name: hostname
      image: adongy/hostname-docker
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: hostname
